//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OML_App
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AchtergrondAppGrijs = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ampbutton = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ampbutton_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int backbutton = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int background1 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int background2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int batterybar = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int batterybutton = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int batterybutton_pressed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bottombox = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int camerabutton = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int camerabutton_pressed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int cancelbutton = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int cancelbutton_pressed = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int connectbutton = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int connectbutton_pressed = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int DialogInterface = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int exitbutton = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int graphview = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Icon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int infobutton = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int interface02 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int joybox = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int joystick = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int joystick_bg = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int livebutton = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int livebutton_pressed = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int menubox = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int menubox2 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int menubox3 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int midbox = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int minibutton = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int minibuttonpressed = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int nhl_logo = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int okbutton = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int okbutton_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int Overview_Carmen = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int Overview_Carmen1 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Overview_Carmen2 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Overview_Carmen3 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int OverViewBG = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int overviewbutton = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int overviewbutton_pressed = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int powerframe = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int recordedbutton = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int recordedbutton_pressed = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int replaybutton = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int settingsbutton = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int settingsbutton_pressed = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int sidebox = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int sidebox2 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int sliderbig = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int sliderBoxL = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int sliderBoxR = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int slidersbox = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int slidersbox0 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int slidersbox1 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int slidersbox2 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int slidersmall = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int startbutton = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int tempbutton = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int tempbutton_pressed = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int voltbutton = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int voltbutton_pressed = 2130837568;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050016
			public const int Accu1Curr = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int Accu1Temp = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int Accu1Voltage = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int Accu2Curr = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int Accu2Temp = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int Accu2Voltage = 2131034138;
			
			// aapt resource value: 0x7f05000a
			public const int EngLF1 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int EngLF2 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int EngLF3 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int EngLR1 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int EngLR2 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int EngLR3 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int EngRF1 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int EngRF2 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int EngRF3 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int EngRR1 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int EngRR2 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int EngRR3 = 2131034133;
			
			// aapt resource value: 0x7f050020
			public const int ampbutton0 = 2131034144;
			
			// aapt resource value: 0x7f050026
			public const int ampbutton1 = 2131034150;
			
			// aapt resource value: 0x7f050021
			public const int amptxt0 = 2131034145;
			
			// aapt resource value: 0x7f050027
			public const int amptxt1 = 2131034151;
			
			// aapt resource value: 0x7f050046
			public const int back_button1 = 2131034182;
			
			// aapt resource value: 0x7f05001c
			public const int battery = 2131034140;
			
			// aapt resource value: 0x7f05002f
			public const int batteryButton = 2131034159;
			
			// aapt resource value: 0x7f05001d
			public const int batterybar = 2131034141;
			
			// aapt resource value: 0x7f05002c
			public const int camera = 2131034156;
			
			// aapt resource value: 0x7f050030
			public const int cameraButton = 2131034160;
			
			// aapt resource value: 0x7f050038
			public const int cancelButton = 2131034168;
			
			// aapt resource value: 0x7f05003f
			public const int connectbutton = 2131034175;
			
			// aapt resource value: 0x7f050036
			public const int dialogText = 2131034166;
			
			// aapt resource value: 0x7f050035
			public const int dialogwindow = 2131034165;
			
			// aapt resource value: 0x7f050007
			public const int flipper = 2131034119;
			
			// aapt resource value: 0x7f05002b
			public const int graphControls = 2131034155;
			
			// aapt resource value: 0x7f05002a
			public const int graphview = 2131034154;
			
			// aapt resource value: 0x7f050044
			public const int ip_adress = 2131034180;
			
			// aapt resource value: 0x7f05003c
			public const int ipaddress = 2131034172;
			
			// aapt resource value: 0x7f050041
			public const int liveButton = 2131034177;
			
			// aapt resource value: 0x7f050002
			public const int menuBox = 2131034114;
			
			// aapt resource value: 0x7f050040
			public const int menuBoxMain = 2131034176;
			
			// aapt resource value: 0x7f050008
			public const int midbox = 2131034120;
			
			// aapt resource value: 0x7f050039
			public const int nhl_image = 2131034169;
			
			// aapt resource value: 0x7f050037
			public const int okButton = 2131034167;
			
			// aapt resource value: 0x7f050009
			public const int overView = 2131034121;
			
			// aapt resource value: 0x7f05002e
			public const int overviewButton = 2131034158;
			
			// aapt resource value: 0x7f05003e
			public const int port = 2131034174;
			
			// aapt resource value: 0x7f050045
			public const int port_adress = 2131034181;
			
			// aapt resource value: 0x7f050006
			public const int powerView0 = 2131034118;
			
			// aapt resource value: 0x7f050032
			public const int powerView1 = 2131034162;
			
			// aapt resource value: 0x7f050042
			public const int recordedButton = 2131034178;
			
			// aapt resource value: 0x7f050000
			public const int relativeLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050043
			public const int settingsButton = 2131034179;
			
			// aapt resource value: 0x7f05002d
			public const int sideBox = 2131034157;
			
			// aapt resource value: 0x7f050005
			public const int sliderControls0 = 2131034117;
			
			// aapt resource value: 0x7f050034
			public const int sliderControls1 = 2131034164;
			
			// aapt resource value: 0x7f050003
			public const int slidersBox0 = 2131034115;
			
			// aapt resource value: 0x7f050031
			public const int slidersBox1 = 2131034161;
			
			// aapt resource value: 0x7f050004
			public const int smallSlider0 = 2131034116;
			
			// aapt resource value: 0x7f050033
			public const int smallSlider1 = 2131034163;
			
			// aapt resource value: 0x7f050001
			public const int startlayout = 2131034113;
			
			// aapt resource value: 0x7f050022
			public const int tempbutton0 = 2131034146;
			
			// aapt resource value: 0x7f050028
			public const int tempbutton1 = 2131034152;
			
			// aapt resource value: 0x7f050023
			public const int temptxt0 = 2131034147;
			
			// aapt resource value: 0x7f050029
			public const int temptxt1 = 2131034153;
			
			// aapt resource value: 0x7f05003a
			public const int textView1 = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int textView2 = 2131034171;
			
			// aapt resource value: 0x7f05003d
			public const int textView3 = 2131034173;
			
			// aapt resource value: 0x7f05001e
			public const int voltbutton0 = 2131034142;
			
			// aapt resource value: 0x7f050024
			public const int voltbutton1 = 2131034148;
			
			// aapt resource value: 0x7f05001f
			public const int volttxt0 = 2131034143;
			
			// aapt resource value: 0x7f050025
			public const int volttxt1 = 2131034149;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Analyse = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Controller = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DialogWindow = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Info = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Live = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Recorded = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Setting = 2130903047;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
