//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OML_App
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AchtergrondAppGrijs = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ampbutton = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ampbutton_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int audiobox = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int audiobutton = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int audiobutton1 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int audiobutton10 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int audiobutton10_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int audiobutton1_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int audiobutton2 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int audiobutton2_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int audiobutton3 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int audiobutton3_pressed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int audiobutton4 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int audiobutton4_pressed = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int audiobutton5 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int audiobutton5_pressed = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int audiobutton6 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int audiobutton6_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int audiobutton7 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int audiobutton7_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int audiobutton8 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int audiobutton8_pressed = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int audiobutton9 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int audiobutton9_pressed = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int audiobutton_pressed = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int backbutton = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int background = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int background1 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int background2 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int basegraph = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int batterybar = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int batterybutton = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int batterybutton_pressed = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int bottombox = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int camerabutton = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int camerabutton_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int cancelbutton = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int cancelbutton_pressed = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int connectbutton = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int connectbutton_pressed = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int controlbutton = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int controlbutton_pressed = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int DialogInterface = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int exitbutton = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int graphview = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int Icon = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int infobutton = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int interface02 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int joybox = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int joystick = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int joystick_bg = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int livebutton = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int livebutton_pressed = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int menubox = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int menubox2 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int menubox3 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int midbox = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int minibutton = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int minibuttonpressed = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int nhl_logo = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int okbutton = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int okbutton_pressed = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int orientbutton = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int orientbutton_pressed = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int Overview_Carmen = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int Overview_Carmen1 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int Overview_Carmen2 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int Overview_Carmen3 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int OverViewBG = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int overviewbutton = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int overviewbutton_pressed = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int pitchbg0 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int pitchbox = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int pitchline = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int pitchline0 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int pitchview0 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int powerframe = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int recordedbutton = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int recordedbutton_pressed = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int releasebutton = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int releasebutton_pressed = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int replaybutton = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int rollline = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int rollline0 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int rollline1 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int settingsbutton = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int settingsbutton_pressed = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int sidebox = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int sidebox2 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int sliderbig = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int sliderBoxL = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int sliderBoxR = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int slidersbox = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int slidersbox0 = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int slidersbox1 = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int slidersbox2 = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int slidersmall = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int spectatebg = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int spectatebutton = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int spectatebutton_pressed = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int startbutton = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int tempbutton = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int tempbutton_pressed = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int viewbutton = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int viewbutton_pressed = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int voltbutton = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int voltbutton_pressed = 2130837611;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050018
			public const int Accu1Curr = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int Accu1Temp = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int Accu1Voltage = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int Accu2Curr = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int Accu2Temp = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int Accu2Voltage = 2131034140;
			
			// aapt resource value: 0x7f05000c
			public const int EngLF1 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int EngLF2 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int EngLF3 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int EngLR1 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int EngLR2 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int EngLR3 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int EngRF1 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int EngRF2 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int EngRF3 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int EngRR1 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int EngRR2 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int EngRR3 = 2131034135;
			
			// aapt resource value: 0x7f05001e
			public const int Throttle0 = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int Throttle1 = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int Throttle2 = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int Throttle3 = 2131034145;
			
			// aapt resource value: 0x7f050044
			public const int aButton1 = 2131034180;
			
			// aapt resource value: 0x7f050046
			public const int aButton2 = 2131034182;
			
			// aapt resource value: 0x7f050048
			public const int aButton3 = 2131034184;
			
			// aapt resource value: 0x7f05004a
			public const int aButton4 = 2131034186;
			
			// aapt resource value: 0x7f05004c
			public const int aButton5 = 2131034188;
			
			// aapt resource value: 0x7f05004e
			public const int aButton6 = 2131034190;
			
			// aapt resource value: 0x7f050050
			public const int aButton7 = 2131034192;
			
			// aapt resource value: 0x7f050052
			public const int aButton8 = 2131034194;
			
			// aapt resource value: 0x7f050054
			public const int aButton9 = 2131034196;
			
			// aapt resource value: 0x7f050045
			public const int aTxt1 = 2131034181;
			
			// aapt resource value: 0x7f050047
			public const int aTxt2 = 2131034183;
			
			// aapt resource value: 0x7f050049
			public const int aTxt3 = 2131034185;
			
			// aapt resource value: 0x7f05004b
			public const int aTxt4 = 2131034187;
			
			// aapt resource value: 0x7f05004d
			public const int aTxt5 = 2131034189;
			
			// aapt resource value: 0x7f05004f
			public const int aTxt6 = 2131034191;
			
			// aapt resource value: 0x7f050051
			public const int aTxt7 = 2131034193;
			
			// aapt resource value: 0x7f050053
			public const int aTxt8 = 2131034195;
			
			// aapt resource value: 0x7f050055
			public const int aTxt9 = 2131034197;
			
			// aapt resource value: 0x7f050026
			public const int ampbutton0 = 2131034150;
			
			// aapt resource value: 0x7f05002c
			public const int ampbutton1 = 2131034156;
			
			// aapt resource value: 0x7f050027
			public const int amptxt0 = 2131034151;
			
			// aapt resource value: 0x7f05002d
			public const int amptxt1 = 2131034157;
			
			// aapt resource value: 0x7f050043
			public const int audiobox = 2131034179;
			
			// aapt resource value: 0x7f050004
			public const int audiobutton = 2131034116;
			
			// aapt resource value: 0x7f050022
			public const int battery = 2131034146;
			
			// aapt resource value: 0x7f050058
			public const int batteryButton = 2131034200;
			
			// aapt resource value: 0x7f050023
			public const int batterybar = 2131034147;
			
			// aapt resource value: 0x7f05006c
			public const int buttonbox0 = 2131034220;
			
			// aapt resource value: 0x7f050036
			public const int camera = 2131034166;
			
			// aapt resource value: 0x7f050059
			public const int cameraButton = 2131034201;
			
			// aapt resource value: 0x7f050061
			public const int cancelButton = 2131034209;
			
			// aapt resource value: 0x7f050068
			public const int connectbutton = 2131034216;
			
			// aapt resource value: 0x7f05005f
			public const int dialogText = 2131034207;
			
			// aapt resource value: 0x7f05005e
			public const int dialogwindow = 2131034206;
			
			// aapt resource value: 0x7f050009
			public const int flipper = 2131034121;
			
			// aapt resource value: 0x7f050035
			public const int graphControls = 2131034165;
			
			// aapt resource value: 0x7f050030
			public const int graphview = 2131034160;
			
			// aapt resource value: 0x7f050065
			public const int ipaddress = 2131034213;
			
			// aapt resource value: 0x7f05006a
			public const int liveButton = 2131034218;
			
			// aapt resource value: 0x7f050034
			public const int maxX = 2131034164;
			
			// aapt resource value: 0x7f050031
			public const int maxY = 2131034161;
			
			// aapt resource value: 0x7f050001
			public const int menuBox = 2131034113;
			
			// aapt resource value: 0x7f050069
			public const int menuBoxMain = 2131034217;
			
			// aapt resource value: 0x7f05000a
			public const int midbox = 2131034122;
			
			// aapt resource value: 0x7f050033
			public const int minX = 2131034163;
			
			// aapt resource value: 0x7f050032
			public const int minY = 2131034162;
			
			// aapt resource value: 0x7f050060
			public const int okButton = 2131034208;
			
			// aapt resource value: 0x7f050082
			public const int onofflinetxt = 2131034242;
			
			// aapt resource value: 0x7f050038
			public const int orient = 2131034168;
			
			// aapt resource value: 0x7f05003d
			public const int orient_maxX = 2131034173;
			
			// aapt resource value: 0x7f05003a
			public const int orient_maxY = 2131034170;
			
			// aapt resource value: 0x7f05003c
			public const int orient_minX = 2131034172;
			
			// aapt resource value: 0x7f05003b
			public const int orient_minY = 2131034171;
			
			// aapt resource value: 0x7f050002
			public const int orientbutton = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int overView = 2131034123;
			
			// aapt resource value: 0x7f050057
			public const int overviewButton = 2131034199;
			
			// aapt resource value: 0x7f05003f
			public const int pitch = 2131034175;
			
			// aapt resource value: 0x7f05003e
			public const int pitchbox = 2131034174;
			
			// aapt resource value: 0x7f050040
			public const int pitchoverlay = 2131034176;
			
			// aapt resource value: 0x7f050067
			public const int port = 2131034215;
			
			// aapt resource value: 0x7f050008
			public const int powerView0 = 2131034120;
			
			// aapt resource value: 0x7f05005b
			public const int powerView1 = 2131034203;
			
			// aapt resource value: 0x7f050062
			public const int relativeLayout1 = 2131034210;
			
			// aapt resource value: 0x7f050003
			public const int releasebutton = 2131034115;
			
			// aapt resource value: 0x7f050041
			public const int roll = 2131034177;
			
			// aapt resource value: 0x7f050039
			public const int rollControls = 2131034169;
			
			// aapt resource value: 0x7f050042
			public const int rolloverlay = 2131034178;
			
			// aapt resource value: 0x7f050056
			public const int sideBox = 2131034198;
			
			// aapt resource value: 0x7f050007
			public const int sliderControls0 = 2131034119;
			
			// aapt resource value: 0x7f05005d
			public const int sliderControls1 = 2131034205;
			
			// aapt resource value: 0x7f050005
			public const int slidersBox0 = 2131034117;
			
			// aapt resource value: 0x7f05005a
			public const int slidersBox1 = 2131034202;
			
			// aapt resource value: 0x7f050006
			public const int smallSlider0 = 2131034118;
			
			// aapt resource value: 0x7f05005c
			public const int smallSlider1 = 2131034204;
			
			// aapt resource value: 0x7f050074
			public const int spec_ampbutton0 = 2131034228;
			
			// aapt resource value: 0x7f050077
			public const int spec_ampbutton1 = 2131034231;
			
			// aapt resource value: 0x7f050071
			public const int spec_battery = 2131034225;
			
			// aapt resource value: 0x7f05007e
			public const int spec_batteryButton = 2131034238;
			
			// aapt resource value: 0x7f050072
			public const int spec_batterybar = 2131034226;
			
			// aapt resource value: 0x7f05007c
			public const int spec_buttonbox = 2131034236;
			
			// aapt resource value: 0x7f05007a
			public const int spec_camera = 2131034234;
			
			// aapt resource value: 0x7f05007f
			public const int spec_cameraButton = 2131034239;
			
			// aapt resource value: 0x7f050079
			public const int spec_graphview = 2131034233;
			
			// aapt resource value: 0x7f05006f
			public const int spec_midbox = 2131034223;
			
			// aapt resource value: 0x7f05007b
			public const int spec_orient = 2131034235;
			
			// aapt resource value: 0x7f05006d
			public const int spec_orientbutton = 2131034221;
			
			// aapt resource value: 0x7f050070
			public const int spec_overView = 2131034224;
			
			// aapt resource value: 0x7f05007d
			public const int spec_overviewButton = 2131034237;
			
			// aapt resource value: 0x7f050075
			public const int spec_tempbutton0 = 2131034229;
			
			// aapt resource value: 0x7f050078
			public const int spec_tempbutton1 = 2131034232;
			
			// aapt resource value: 0x7f050073
			public const int spec_voltbutton0 = 2131034227;
			
			// aapt resource value: 0x7f050076
			public const int spec_voltbutton1 = 2131034230;
			
			// aapt resource value: 0x7f050083
			public const int spectateButton = 2131034243;
			
			// aapt resource value: 0x7f05006e
			public const int spectateflipper = 2131034222;
			
			// aapt resource value: 0x7f050000
			public const int startlayout = 2131034112;
			
			// aapt resource value: 0x7f050028
			public const int tempbutton0 = 2131034152;
			
			// aapt resource value: 0x7f05002e
			public const int tempbutton1 = 2131034158;
			
			// aapt resource value: 0x7f050029
			public const int temptxt0 = 2131034153;
			
			// aapt resource value: 0x7f05002f
			public const int temptxt1 = 2131034159;
			
			// aapt resource value: 0x7f050063
			public const int textView1 = 2131034211;
			
			// aapt resource value: 0x7f050064
			public const int textView2 = 2131034212;
			
			// aapt resource value: 0x7f050066
			public const int textView3 = 2131034214;
			
			// aapt resource value: 0x7f050037
			public const int vidview = 2131034167;
			
			// aapt resource value: 0x7f05006b
			public const int viewerButton = 2131034219;
			
			// aapt resource value: 0x7f050080
			public const int viewerLayout = 2131034240;
			
			// aapt resource value: 0x7f050081
			public const int viewertxt = 2131034241;
			
			// aapt resource value: 0x7f050024
			public const int voltbutton0 = 2131034148;
			
			// aapt resource value: 0x7f05002a
			public const int voltbutton1 = 2131034154;
			
			// aapt resource value: 0x7f050025
			public const int volttxt0 = 2131034149;
			
			// aapt resource value: 0x7f05002b
			public const int volttxt1 = 2131034155;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Controller = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DialogWindow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Live = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Spectate = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Viewer = 2130903045;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
