//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OML_App
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AchtergrondAppGrijs = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int backbutton = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bottombox = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int connectbutton = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int exitbutton = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int infobutton = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int interface02 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int joybox = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int joystick = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int joystick_bg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int livebutton = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int menubox = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int menubox2 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int minibutton = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int minibuttonpressed = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int nhl_logo = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int recordedbutton = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int replaybutton = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int settingsbutton = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int sidebox = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int sidebox2 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int sliderbig = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int slidersbox = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int slidersbox2 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int slidersmall = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int startbutton = 2130837531;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050022
			public const int back_button1 = 2131034146;
			
			// aapt resource value: 0x7f05000f
			public const int battery = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int battext = 2131034128;
			
			// aapt resource value: 0x7f05000a
			public const int bigSlider = 2131034122;
			
			// aapt resource value: 0x7f050011
			public const int bottomBox = 2131034129;
			
			// aapt resource value: 0x7f05001b
			public const int connectbutton = 2131034139;
			
			// aapt resource value: 0x7f05000c
			public const int flipper = 2131034124;
			
			// aapt resource value: 0x7f050014
			public const int gameControls1 = 2131034132;
			
			// aapt resource value: 0x7f050020
			public const int ip_adress = 2131034144;
			
			// aapt resource value: 0x7f050018
			public const int ipaddress = 2131034136;
			
			// aapt resource value: 0x7f050013
			public const int joyBox = 2131034131;
			
			// aapt resource value: 0x7f05001d
			public const int liveButton = 2131034141;
			
			// aapt resource value: 0x7f050002
			public const int menuBox = 2131034114;
			
			// aapt resource value: 0x7f05001c
			public const int menuBoxMain = 2131034140;
			
			// aapt resource value: 0x7f050015
			public const int nhl_image = 2131034133;
			
			// aapt resource value: 0x7f05000d
			public const int overView = 2131034125;
			
			// aapt resource value: 0x7f05001a
			public const int port = 2131034138;
			
			// aapt resource value: 0x7f050021
			public const int port_adress = 2131034145;
			
			// aapt resource value: 0x7f05001e
			public const int recordedButton = 2131034142;
			
			// aapt resource value: 0x7f050000
			public const int relativeLayout1 = 2131034112;
			
			// aapt resource value: 0x7f05001f
			public const int settingsButton = 2131034143;
			
			// aapt resource value: 0x7f050012
			public const int sideBox = 2131034130;
			
			// aapt resource value: 0x7f050003
			public const int sliderButton = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int sliderControls1 = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int sliderControls2 = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int sliderControls3 = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int slidersBox = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int smallSlider0 = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int smallSlider1 = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int smallSliderLayout = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int startlayout = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int testtext = 2131034126;
			
			// aapt resource value: 0x7f050016
			public const int textView1 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int textView2 = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int textView3 = 2131034137;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Analyse = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Controller = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Info = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Live = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Recorded = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Setting = 2130903046;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
